There was an exception
Executed 
Test completed
